import { writeFile } from "node:fs/promises";
import { join } from "node:path";
import {
    DEFAULT_LOCALE,
    DOWNLOAD_PAGES,
    LOCALE_META,
    SITE_ORIGIN,
    STATIC_PAGES,
    SUPPORTED_LOCALES,
    downloadPath,
    pagePath,
} from "./docs-config.mjs";
import { collectLocalizedDocMeta, repoRoot } from "./docs-utils.mjs";

const generatedPath = join(repoRoot, "src/docs/generated.js");
const sitemapPath = join(repoRoot, "public/sitemap.xml");

const escapeXml = (value) =>
    String(value)
        .replace(/&/g, "&amp;")
        .replace(/"/g, "&quot;")
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;");

const docPath = (doc, locale = DEFAULT_LOCALE) => {
    const basePath = pagePath("document", locale);

    return doc.slug ? `${basePath}/${doc.slug}` : basePath;
};

const renderGeneratedModule = (docs) => {
    const pages = docs.map(({ id, slug, file, category, order }) => ({
        id,
        slug,
        file,
        category,
        order,
    }));
    const categories = [
        ...new Map(
            docs.map(({ category, categoryOrder, categoryMeta }) => [
                category,
                {
                    id: category,
                    order: categoryOrder,
                    meta: categoryMeta,
                },
            ]),
        ).values(),
    ].sort((a, b) => a.order - b.order);
    const meta = Object.fromEntries(
        docs.map(({ id, meta: localizedMeta }) => [id, localizedMeta]),
    );

    return `// Generated by scripts/generate-docs.mjs. Do not edit by hand.

export const DOC_CATEGORIES = ${JSON.stringify(categories, null, 4)};

export const DOC_PAGES = ${JSON.stringify(pages, null, 4)};

export const DOC_PAGE_META = ${JSON.stringify(meta, null, 4)};

export const DEFAULT_DOC_PAGE = DOC_PAGES[0].id;
`;
};

const renderAlternateLinks = (pathForLocale) =>
    [
        ...SUPPORTED_LOCALES.map((locale) => {
            const hreflang = LOCALE_META[locale].htmlLang;
            const href = `${SITE_ORIGIN}${pathForLocale(locale)}`;

            return `        <xhtml:link rel="alternate" hreflang="${escapeXml(hreflang)}" href="${escapeXml(href)}" />`;
        }),
        `        <xhtml:link rel="alternate" hreflang="x-default" href="${escapeXml(`${SITE_ORIGIN}${pathForLocale(DEFAULT_LOCALE)}`)}" />`,
    ].join("\n");

const renderUrl = (loc, pathForLocale) => `    <url>
        <loc>${escapeXml(loc)}</loc>
        <lastmod>2026-05-27</lastmod>
${renderAlternateLinks(pathForLocale)}
    </url>`;

const renderSitemap = (docs) => {
    const urls = [];

    for (const page of STATIC_PAGES) {
        for (const locale of SUPPORTED_LOCALES) {
            urls.push(
                renderUrl(
                    `${SITE_ORIGIN}${pagePath(page, locale)}`,
                    (nextLocale) => pagePath(page, nextLocale),
                ),
            );
        }
    }

    for (const downloadPage of DOWNLOAD_PAGES) {
        for (const locale of SUPPORTED_LOCALES) {
            urls.push(
                renderUrl(
                    `${SITE_ORIGIN}${downloadPath(downloadPage.id, locale)}`,
                    (nextLocale) => downloadPath(downloadPage.id, nextLocale),
                ),
            );
        }
    }

    for (const doc of docs) {
        for (const locale of SUPPORTED_LOCALES) {
            urls.push(
                renderUrl(
                    `${SITE_ORIGIN}${docPath(doc, locale)}`,
                    (nextLocale) => docPath(doc, nextLocale),
                ),
            );
        }
    }

    return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
    xmlns:xhtml="http://www.w3.org/1999/xhtml">
${urls.join("\n")}
</urlset>
`;
};

const docs = await collectLocalizedDocMeta();

await writeFile(generatedPath, renderGeneratedModule(docs));
await writeFile(sitemapPath, renderSitemap(docs));

console.log(`Generated ${docs.length} docs into src/docs/generated.js`);
console.log("Generated public/sitemap.xml");
